#!/bin/bash
 srun -N 4 -n 4 hostname
#SBATCH --error=job.err --output=job.out
srun -n 4 hostname
#SBATCH --error=job.err --output=job.out
srun -n 4 hostname
#SBATCH --error=job.err --output=job.out
srun -n 4 hostname
#SBATCH --error=job.err --output=job.out
srun -n 4 hostname
#SBATCH --error=job.err --output=job.out
srun -n 4 hostname
#SBATCH --error=job.err --output=job.out
srun -n 4 hostname
#SBATCH --error=job.err --output=job.out
srun -n 4 hostname
#SBATCH --error=job.err --output=job.out
srun -n 4 hostname
#SBATCH --error=job.err --output=job.out
srun -n 4 hostname

