
all: 1.1.x 1.2.x 1.3.x 1.4.x

clean:
	rm *.x
1.1.x:
	gcc -fopenmp 1.1.c -o 1.1.x -lrt
1.2.x:
	gcc -fopenmp 1.2.c -o 1.2.x -lrt
1.3.x:
	gcc -fopenmp 1.3.c -o 1.3.x -lrt
1.4.x:
	gcc -fopenmp 1.4.c -o 1.4.x -lrt
